/** Sample webhook payloads for testing */

const TIMESTAMP = new Date().toISOString();

export const EVENT_FIXTURES: Record<string, Record<string, unknown>> = {
  'payment_request.completed': {
    event: 'payment_request.completed',
    payment_request_id: 'pr_test_' + randomId(),
    charge_id: 'ch_test_' + randomId(),
    amount: '100.00',
    currency: 'SGD',
    status: 'completed',
    payment_method: 'paynow_online',
    reference_number: 'REF-' + randomId(),
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'payment_request.failed': {
    event: 'payment_request.failed',
    payment_request_id: 'pr_test_' + randomId(),
    amount: '50.00',
    currency: 'SGD',
    status: 'failed',
    payment_method: 'card',
    reference_number: 'REF-' + randomId(),
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'charge.created': {
    event: 'charge.created',
    charge_id: 'ch_test_' + randomId(),
    payment_request_id: 'pr_test_' + randomId(),
    amount: '75.00',
    currency: 'SGD',
    status: 'succeeded',
    payment_method: 'grabpay_direct',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'charge.updated': {
    event: 'charge.updated',
    charge_id: 'ch_test_' + randomId(),
    amount: '75.00',
    currency: 'SGD',
    status: 'completed',
    payment_method: 'grabpay_direct',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'transfer.paid': {
    event: 'transfer.paid',
    transfer_id: 'tr_test_' + randomId(),
    amount: '500.00',
    currency: 'SGD',
    status: 'paid',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'transfer.failed': {
    event: 'transfer.failed',
    transfer_id: 'tr_test_' + randomId(),
    amount: '500.00',
    currency: 'SGD',
    status: 'failed',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'payout.created': {
    event: 'payout.created',
    payout_id: 'po_test_' + randomId(),
    amount: '1000.00',
    currency: 'SGD',
    status: 'pending',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'order.created': {
    event: 'order.created',
    order_id: 'ord_test_' + randomId(),
    amount: '250.00',
    currency: 'SGD',
    status: 'pending',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'order.updated': {
    event: 'order.updated',
    order_id: 'ord_test_' + randomId(),
    amount: '250.00',
    currency: 'SGD',
    status: 'completed',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'invoice.created': {
    event: 'invoice.created',
    invoice_id: 'inv_test_' + randomId(),
    amount: '500.00',
    currency: 'SGD',
    status: 'pending',
    customer_email: 'test@example.com',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'transfer.created': {
    event: 'transfer.created',
    transfer_id: 'tr_test_' + randomId(),
    amount: '300.00',
    currency: 'SGD',
    status: 'created',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'transfer.updated': {
    event: 'transfer.updated',
    transfer_id: 'tr_test_' + randomId(),
    amount: '300.00',
    currency: 'SGD',
    status: 'processing',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'transfer.processing': {
    event: 'transfer.processing',
    transfer_id: 'tr_test_' + randomId(),
    amount: '300.00',
    currency: 'SGD',
    status: 'processing',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'transfer.scheduled': {
    event: 'transfer.scheduled',
    transfer_id: 'tr_test_' + randomId(),
    amount: '300.00',
    currency: 'SGD',
    status: 'scheduled',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'transfer.canceled': {
    event: 'transfer.canceled',
    transfer_id: 'tr_test_' + randomId(),
    amount: '300.00',
    currency: 'SGD',
    status: 'canceled',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'recurring_billing.method_attached': {
    event: 'recurring_billing.method_attached',
    recurring_billing_id: 'rb_test_' + randomId(),
    payment_method: 'card',
    status: 'active',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'recurring_billing.method_detached': {
    event: 'recurring_billing.method_detached',
    recurring_billing_id: 'rb_test_' + randomId(),
    payment_method: 'paynow_online',
    status: 'active',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
  'recurring_billing.subscription_updated': {
    event: 'recurring_billing.subscription_updated',
    recurring_billing_id: 'rb_test_' + randomId(),
    status: 'cancelled',
    hmac: 'test_signature',
    created_at: TIMESTAMP,
  },
};

export const AVAILABLE_EVENTS = Object.keys(EVENT_FIXTURES);

function randomId(): string {
  return Math.random().toString(36).slice(2, 10);
}
